# Generated by Django 5.0.14 on 2026-08-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the journal entry.', max_length=255)),
                ('content', models.TextField(help_text='Content or reflection body of the journal entry.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entry was last updated.')),
                ('user', models.ForeignKey(help_text='The authenticated user who owns this journal entry.', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
