# Generated by Django 5.0.14 on 2026-08-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomBotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField(help_text='The user prompt or question sent to BloomBot.')),
                ('ai_response', models.TextField(help_text='The response generated by BloomBot.')),
                ('feedback_type', models.CharField(choices=[('Helpful', 'Helpful'), ('Not Helpful', 'Not Helpful')], help_text='Whether the response was marked Helpful or Not Helpful.', max_length=20)),
                ('selected_reasons', models.JSONField(blank=True, default=list, help_text='List of selected reasons for the feedback.')),
                ('optional_comment', models.TextField(blank=True, default='', help_text='Optional feedback comment provided by the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when feedback was submitted.')),
                ('user', models.ForeignKey(blank=True, help_text='The authenticated user submitting feedback.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloombot_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BloomBot Feedback',
                'verbose_name_plural': 'BloomBot Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
