# Generated by Django 5.0.14 on 2026-08-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Happy', 'Happy 😊'), ('Calm', 'Calm 😌'), ('Excited', 'Excited 🤩'), ('Grateful', 'Grateful 🌸'), ('Neutral', 'Neutral 😐'), ('Tired', 'Tired 😴'), ('Stressed', 'Stressed 😖'), ('Anxious', 'Anxious 😰'), ('Sad', 'Sad 😔'), ('Angry', 'Angry 😠')], help_text='The selected emotion state (e.g., Happy, Calm, Sad).', max_length=50)),
                ('note', models.TextField(blank=True, help_text='Optional note or context explaining the mood.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the mood entry was recorded.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the mood entry was last modified.')),
                ('user', models.ForeignKey(help_text='The authenticated user recording their mood.', on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
