# Generated by Django 5.0.14 on 2026-08-11 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, help_text='Mood score from 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
