# Generated by Django 5.0.14 on 2026-08-11 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_mood_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, help_text='Overall mood score rating from 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
