# Generated by Django 5.0.14 on 2026-08-07 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(help_text='Category of the story (e.g. Anxiety, Stress, Burnout, etc.).', max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(help_text='Body content of the story.'),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the story was created.'),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Whether the author requested to publish anonymously.'),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='Whether this story has been reported by a community member.'),
        ),
        migrations.AlterField(
            model_name='story',
            name='report_reason',
            field=models.CharField(blank=True, help_text='Reason provided if the story was reported.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(help_text='Title of the story.', max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the story was last updated.'),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created this story. Nullable for anonymous guest stories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
