# Generated by Django 5.0.14 on 2026-08-07 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gratitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gratitude', models.TextField(help_text='The text of the gratitude entry.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entry was last updated.')),
                ('user', models.ForeignKey(help_text='The authenticated user who recorded this gratitude.', on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gratitude',
                'verbose_name_plural': 'Gratitudes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_talk', models.TextField(help_text='The text of the self-talk entry.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entry was last updated.')),
                ('user', models.ForeignKey(help_text='The authenticated user who recorded this self-talk.', on_delete=django.db.models.deletion.CASCADE, related_name='selftalk_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Self-Talk',
                'verbose_name_plural': 'Self-Talks',
                'ordering': ['-created_at'],
            },
        ),
    ]
