# Generated by Django 5.0.14 on 2026-08-09 21:29

from django.db import migrations, models
import django.utils.timezone


def populate_reflection_date(apps, schema_editor):
    Gratitude = apps.get_model('reflection', 'Gratitude')
    SelfTalk = apps.get_model('reflection', 'SelfTalk')
    
    for g in Gratitude.objects.all():
        if g.created_at:
            local_dt = django.utils.timezone.localtime(g.created_at)
            g.reflection_date = local_dt.date()
        else:
            g.reflection_date = django.utils.timezone.now().date()
        g.save(update_fields=['reflection_date'])

    for st in SelfTalk.objects.all():
        if st.created_at:
            local_dt = django.utils.timezone.localtime(st.created_at)
            st.reflection_date = local_dt.date()
        else:
            st.reflection_date = django.utils.timezone.now().date()
        st.save(update_fields=['reflection_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitude',
            name='reflection_date',
            field=models.DateField(null=True, help_text='The calendar date this reflection belongs to.'),
        ),
        migrations.AddField(
            model_name='selftalk',
            name='reflection_date',
            field=models.DateField(null=True, help_text='The calendar date this reflection belongs to.'),
        ),
        migrations.RunPython(populate_reflection_date, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='gratitude',
            name='reflection_date',
            field=models.DateField(help_text='The calendar date this reflection belongs to.'),
        ),
        migrations.AlterField(
            model_name='selftalk',
            name='reflection_date',
            field=models.DateField(help_text='The calendar date this reflection belongs to.'),
        ),
    ]