# Generated by Django 5.0.14 on 2026-08-11 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0002_auto_20260809_2129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitude',
            name='user',
            field=models.ForeignKey(help_text='The user who created this gratitude entry.', on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selftalk',
            name='user',
            field=models.ForeignKey(help_text='The user who created this self-talk entry.', on_delete=django.db.models.deletion.CASCADE, related_name='selftalk_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
