from django.db import models
from django.contrib.auth.models import User


class FeedbackType(models.TextChoices):
    HELPFUL = 'Helpful', 'Helpful'
    NOT_HELPFUL = 'Not Helpful', 'Not Helpful'


class BloomBotFeedback(models.Model):
    """
    Model representing user feedback (Helpful / Not Helpful) on BloomBot AI responses.
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='bloombot_feedbacks',
        null=True,
        blank=True,
        help_text="The authenticated user submitting feedback."
    )
    user_prompt = models.TextField(
        help_text="The user prompt or question sent to BloomBot."
    )
    ai_response = models.TextField(
        help_text="The response generated by BloomBot."
    )
    feedback_type = models.CharField(
        max_length=20,
        choices=FeedbackType.choices,
        help_text="Whether the response was marked Helpful or Not Helpful."
    )
    selected_reasons = models.JSONField(
        default=list,
        blank=True,
        help_text="List of selected reasons for the feedback."
    )
    optional_comment = models.TextField(
        blank=True,
        default='',
        help_text="Optional feedback comment provided by the user."
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when feedback was submitted."
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'BloomBot Feedback'
        verbose_name_plural = 'BloomBot Feedbacks'

    def __str__(self):
        return f"{self.feedback_type} by {self.user.email if self.user else 'Anonymous'} at {self.created_at.strftime('%Y-%m-%d %H:%M')}"
