# Generated by Django 5.0.14 on 2026-08-07 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text of the gentle affirmation')),
                ('author', models.CharField(blank=True, default='MindBloom', help_text='Author or source', max_length=255, null=True)),
                ('category', models.CharField(default='General', help_text='Category or theme', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this affirmation is active for daily selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Affirmation',
                'verbose_name_plural': 'Affirmations',
                'db_table': 'affirmations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the wellness article', max_length=255)),
                ('summary', models.TextField(help_text='Short summary or teaser of the article')),
                ('content', models.TextField(help_text='Full body content of the article')),
                ('image', models.URLField(blank=True, help_text='Optional header image URL', max_length=1024, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the newsletter', max_length=255)),
                ('content', models.TextField(help_text='Body content of the newsletter')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text of the inspirational quote')),
                ('author', models.CharField(blank=True, default='Anonymous', help_text='Author of the quote', max_length=255, null=True)),
                ('category', models.CharField(default='Mindfulness', help_text='Category or theme', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this quote is active for daily selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
