# Generated by Django 5.0.14 on 2026-08-08 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous Reviewer', help_text='Author name', max_length=255)),
                ('role', models.CharField(default='MindBloom User', help_text='Role or title', max_length=255)),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5')),
                ('quote', models.TextField(help_text='Testimonial or review text')),
                ('avatar', models.CharField(blank=True, default='', help_text='Avatar image URL', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
