# Generated by Django 5.0.14 on 2026-08-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0002_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Self Care', max_length=100),
        ),
    ]
