# Generated by Django 5.0.14 on 2026-08-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0003_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
